version: '3.8'

services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: electoral-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/electoral_results?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRATION=24h
      - BLOCKCHAIN_RPC_URL=https://polygon-rpc.com
      - SMART_CONTRACT_ADDRESS=0x0000000000000000000000000000000000000000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - electoral-network

  mongodb:
    image: mongo:7.0
    container_name: electoral-mongodb
    restart: unless-stopped
    ports:
      - '27019:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=electoral_results
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - electoral-network

  redis:
    image: redis:7.2-alpine
    container_name: electoral-redis-yo-custodio
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - electoral-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: electoral-mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    networks:
      - electoral-network

volumes:
  mongodb_data:
  redis_data:

networks:
  electoral-network:
    driver: bridge